os: linux
dist: focal
language: node_js
node_js: node

jobs:
  include:
    - addons:
        chrome: "stable"
        firefox: "latest"
        apt:
          packages:
            - libnss3
      services:
        - xvfb
      before_install:
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get -q update
        - sudo apt-get -y install python3.10
        - python --version
        - mkdir qunit
        - wget -O qunit/qunit-1.18.0.css http://code.jquery.com/qunit/qunit-1.18.0.css
        - wget -O qunit/qunit-1.18.0.js  http://code.jquery.com/qunit/qunit-1.18.0.js
        - npm install testem
        - ./node_modules/.bin/testem launchers
      before_script:
        - (cd scripts && python3.10 make_doc.py)
        - (cd scripts && python3.10 make_dist.py)

      script:
        - ./node_modules/.bin/testem --launch "Firefox,Headless Chrome" -t www/tests/qunit/run_tests.html ci

    - language: python
      python: 3.9
      before_install: pip install --upgrade pip
      before_script: pip install flake8
      script:
        - EXCLUDE=./.*,www/src/Lib/test/badsyntax_3131.py
        # stop the build if there are Python syntax errors
        - flake8 . --exclude=$EXCLUDE --exit-zero --select=E999 --show-source --statistics
