name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  browser-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Install testem
        run: |
          npm install testem
          ./node_modules/.bin/testem launchers

      - name: Build docs and dist
        run: |
          (cd scripts && python3 make_doc.py)
          (cd scripts && python3 make_dist.py)

      # Some day, put back Chrome or "Headless Chrome" as well. For some reason
      # as of 2022 Aug 23, the testem websocket connection is sometimes reset,
      # which prevents the browser from reporting results to the testem process
      # when running on Chrome.
      - name: Run browser tests
        run: xvfb-run --auto-servernum ./node_modules/.bin/testem --launch Firefox -t www/tests/run_tests.html ci

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8

      # stop the build if there are Python syntax errors or undefined names
      - name: Run flake8
        run: |
          flake8 --builtins=__BRYTHON__ \
            --exclude='./.*,www/src/Lib,www/tests' \
            --select=E9,F63,F7,F82 --show-source --statistics
